version: '3.9'

services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ~/database/xyz:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: watchdog
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRESQL_ENABLE_TLS: 'yes'
  api:
    build: .
    volumes:
      - ./appsettings/appsettings.json:/workdir/appsettings/appsettings.json
      - ./secrets/secrets.json:/workdir/secrets/secrets.json
    ports:
      - 8080:8080
    links:
      - postgres
    depends_on:
      - postgres
